version: 1.0.{build}

# Указываем что это Node.js проект
build: off

# Устанавливаем Node.js
install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version

# Тестирование и сборка
test_script:
  - npm ci
  - npm list nuxt
  - npm run build

# Артефакты для деплоя
artifacts:
  - path: .nuxt/dist/**/*
    name: dist

# Уведомления
notifications:
  - provider: Email
    to:
      - fkupme@yandex.ru
    on_build_success: false
    on_build_failure: true
